id: P008046
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:57:44.198744
source_metadata:
  id: bdr:W5424
  title: གསུང་འབུམ། འཇིགས་མེད་བསམ་གཏན
  author: ''
  volumes:
    b4a7e6d14ac14847baed91c0af888411:
      image_group_id: I5401
      title: ''
      volume_number: 1
      total_pages: 870
      base_file: v001.txt
    ee33128af047468b9a6b4a555a142e16:
      image_group_id: I5402
      title: ''
      volume_number: 2
      total_pages: 960
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
