id: P008046
initial_creation_type: ocr
source_metadata:
  id: bdr:W5424
  title: གསུང་འབུམ། འཇིགས་མེད་བསམ་གཏན
  author: ''
  volumes:
    b4a7e6d14ac14847baed91c0af888411:
      image_group_id: I5401
      title: ''
      volume_number: 1
      total_pages: 870
    ee33128af047468b9a6b4a555a142e16:
      image_group_id: I5402
      title: ''
      volume_number: 2
      total_pages: 960
ebook_metadata:
  title: གསུང་འབུམ། འཇིགས་མེད་བསམ་གཏན
  author: ''
  sku: P008046
  cover: cover.jpg
  layers:
  - pagination
