id: I8D10060C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:46:16+00:00'
last_modified: '2022-06-08T18:02:48.020902+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W5424
  title: གསུང་འབུམ། འཇིགས་མེད་བསམ་གཏན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BF07:
      image_group_id: I5401
      title: ''
      total_pages: 870
      order: 1
      base_file: BF07.txt
    F976:
      image_group_id: I5402
      title: ''
      total_pages: 960
      order: 2
      base_file: F976.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
