id: I8D10060C
legacy_id: P008046
ocr_import_info:
  bdrc_scan_id: W5424
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T04:44:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:00:49.663717+00:00'
last_modified: 2022-09-04 11:01:39.300152
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W5424
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW5424
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་བསམ་གཏན།
  author: རྫོང་དཀར་གྲུབ་དབང་འཇིགས་མེད་བསམ་གཏན།
statistics:
  ocr_word_mean_confidence_index: 0.5462735583149846
  ocr_word_median_confidence_index: 0.5199999809265137
quality: null
bases:
  I5401:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5401
      total_pages: 870
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5401.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5511231808107584
    legacy_id: v001
  I5402:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5402
      total_pages: 960
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5402.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5418798438311043
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
